items = [
    {'name':'scuba_diver', 
    'price': 10},
    {'name': 'green_plant',
    'price' : 2},
    {'name': 'sand_castle',
    'price': 30},
    {'name': 'item_3',
    'price': 50},
    {'name': 'item_4',
    'price': 50},
    {'name': 'item_5',
    'price': 50},
    {'name': 'item_6',
    'price': 50},
    {'name': 'item_7',
    'price': 50},
    {'name': 'item_8',
    'price': 50},
    {'name': 'item_9',
    'price': 50},
    {'name': 'item_10',
    'price': 50},
    {'name': 'item_11',
    'price': 50},   
    ]   
tanks = [
    {'name':'fish_bowl',
    'price': 30},
    {'name': 'basic_aquarium',
    'price': 200},
    {'name': 'royal_aquarium',
    'price': 1000},
    {'name': 'magestic_koi_pond',
    'price': 2000}]