items = [
    {'name':'sand_castle', 
    'price': 50},
    {'name': 'shell',
    'price' : 10},
    {'name': 'umbrella',
    'price': 30},
    {'name': 'table',
    'price': 50},
    {'name': 'tv',
    'price': 60},
    {'name': 'chair',
    'price': 40},
    {'name': 'lamp',
    'price': 20},
    {'name': 'fruit_basket',
    'price': 50},
    {'name': 'item_8',
    'price': 50},
    {'name': 'item_9',
    'price': 50},
    {'name': 'item_10',
    'price': 50},
    {'name': 'item_11',
    'price': 50},   
    ]   
tanks = [
    {'name': 'bag',
    'tier':0,
    'price': 0},
    {'name':'fish_bowl',
    'tier': 1,
    'price': 100},
    {'name': 'basic_aquarium',
    'tier': 2,
    'price': 500},
    {'name': 'wide_aquarium',
    'tier': 3,
    'price': 1000},]