items = [
    {'name':'scuba_diver', 
    'price': 10},
    {'name': 'green_plant',
    'price' : 2},
    {'name': 'sand_castle',
    'price': 30},
    {'name': 'item_3',
    'price': 50},
    {'name': 'item_4',
    'price': 50},
    {'name': 'item_5',
    'price': 50},
    {'name': 'item_6',
    'price': 50},
    {'name': 'item_7',
    'price': 50},
    {'name': 'item_8',
    'price': 50},
    {'name': 'item_9',
    'price': 50},
    {'name': 'item_10',
    'price': 50},
    {'name': 'item_11',
    'price': 50},   
    ]   
tanks = [
    {'name': 'bag',
    'tier':0,
    'price': 0},
    {'name':'fish_bowl',
    'tier': 1,
    'price': 100},
    {'name': 'basic_aquarium',
    'tier': 2,
    'price': 500},
    {'name': 'wide_aquarium',
    'tier': 3,
    'price': 1000},]